name: aca_assist
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.4
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.3.0
  flutter_svg: ^2.0.17
  url_launcher: ^6.3.1
  google_generative_ai: ^0.4.6
  http: ^1.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Icon.png
    - assets/logo.png
    - assets/google-logo.png
    - assets/home_logo.svg
    - assets/tasks_logo.svg
    - assets/analytics_logo.svg
    - assets/mic_logo.svg
    - assets/settings_logo.svg
    - assets/todo_logo.svg
    - assets/schedule_logo.svg

flutter_icons:
  image_path: "assets/Icon.png"
  adaptive_icon_background: "#5C6B7D"
  adaptive_icon_foreground: "assets/Icon.png"
  ios: true
  android: true